### ISSUE TITLE
apps.plugin enhancements

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#146]
Based on the issues opened so far, `apps.plugin` is candidate for the following enhancements:

- [x] per user charts #85, #106  
- [x] per group charts, #106 
- [x] grouping of processes based on patterns matching the whole command lines (read from `/proc/X/cmdline`, #142 
- ~~per cgroups charts, #91~~ (implemented cgroups plugin at the core of netdata)
- [x] `apps_groups.conf` gets overwritten with `make install` #209 
- [x] drop root privileges from `apps.plugin` and use capabilities #157 
- [x] apps.plugin should not log to syslog #225 
- [x] apps.plugin should account exited children information too #626

**Comment by Sachiru** [comment]
Certain processes (ZFS, i.e.) are spawned in a certain pattern, for example:

z_wr_* (where * is a number), and
z_rd_* (where * is a number).

Is there any way to support these cases?

**Comment by ktsaou** [comment]
> Certain processes (ZFS, i.e.) are spawned in a certain pattern

the 3rd bullet in the description of the issue

**Comment by ktsaou** [comment]
WIth the https://github.com/firehol/netdata/commit/da9e1df4cbde9208d30b99937046b667e82e88a1 commit, the following have been added:

1. Per user charts (all of the previously known as Apps Charts: cpu, memory, disk, files, sockets, pipes, swap, etc)

  these were tricky, because:
  -  I had to find a way to detect the username of all running pids without reading all the thousands of the `/proc/X/status` files. It turns out that just examining each pid /proc directory `/proc/X` (without reading any files), I could get the effective uid and gid of the process - this is very fast, just this addition did not have any impact on the profiler, and
  - tasks switch users all the time (especially samba - every few seconds), so the incremental resources consumed were transferred among users and resulted in unrealistic spikes in the charts (I solved it of course, but it required some treatment).

2. Per user group charts (all of them again)

 similar to the above - same things

3. Almost total re-write of `apps.plugin`.

  The new one is optimized too. It is 10% faster, **after the new features**, compared to the old.

4. Solved a few corner cases that were unhandled in the previous version.

Enjoy!

**Comment by ktsaou** [comment]
Pattern matching of processes has been implemented. Please read #251

**Comment by ktsaou** [comment]
`apps_groups.conf` is now preserved with https://github.com/ktsaou/netdata/commit/e35c0f5b275b55e04bcc0bdb7793332005912911

**Comment by ktsaou** [comment]
this is now complete.
